name: Docs

on:
  push:
    branches:
      - master  # Set a branch name to trigger deployment

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
      
    - name: Doxygen Action
      uses: mattnotmitt/doxygen-action@v1.1.0
      with:
        # Path to Doxyfile
        doxyfile-path: ./Doxyfile
        # Working directory
        working-directory: .
      
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3.7.0-8
      with:
        personal_token: ${{ secrets.PERSONAL_TOKEN }}
        external_repository: alyukovnet/alyukovnet
        destination_dir: ./string
        publish_dir: ./docs
        publish_branch: gh-pages
